package std
import "path/filepath"

var mimeTypes = map[string]string{
	".aac":   "audio/aac",
	".avi":   "video-x-msvideo",
	".bz":    "application/x-bzip",
	".bz2":   "application/x-bzip2",
	".csh":   "application/x-csh",
	".css":   "text/css",
	".doc":   "application/msword",
	".docx":  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".gif":   "image/gif",
	".html":  "text/html",
	".htm":   "text/html",
	".ico":   "image/x-icon",
	".jar":   "application/java-archive",
	".js":    "text/javascript",
	".json":  "application/json",
	".mjs":   "text/javascript",
	".mp3":   "audio/mpeg",
	".mp4":   "video/mp4",
	".mpeg":  "video/mpeg",
	".odp":   "application/vnd.oasis.opendocument.presentation",
	".ods":   "application/vnd.oasis.opendocument.spreadsheet",
	".odt":   "application/vnd.oasis.opendocument.text",
	".oga":   "audio/ogg",
	".ogv":   "video/ogg",
	".txt":   "text/plain",
	".otf":   "font/otf",
	".png":   "image/png",
	".pdf":   "application/pdf",
	".php":   "application/x-httpd-php",
	".ppt":   "application/vnd.ms-powerpoint",
	".pptx":  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	".rar":   "application/vnd.rar",
	".rtf":   "application/rtf",
	".sh":    "application/x-sh",
	".svg":   "image/svg+xml",
	".tar":   "application/x-tar",
	".tiff":  "image/tiff",
	".tf":    "image/tiff",
	".ttf":   "font/ttf",
	".wav":   "audio/wav",
	".weba":  "audio/webm",
	".webm":  "video/webm",
	".webp":  "image/webp",
	".xhtml": "application/xhtml+xml", //Why tf would anyone use this
	".xls":   "application/vnd.ms-excel",
	".xlsx":  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".xml":   "application/xml",
	".xul":   "application/vnd.mozilla.xul+xml",
	".zip":   "application/zip",
	".7z":    "application/x-7z-compressed",
	".atom": "application/atom+xml",
	".atomcat": "application/atomcat+xml",
	".ecma": "application/ecmascript",
	".gz": "application/gzip",
	".tgz": "application/gzip",
	".class": "application/java-vm",
	".dot": "application/msword",
	".wiz": "application/msword",
	".pgp": "application/pgp-encrypted",
	".apk": "application/vnd.android.package-archive",
	".deb": "application/vnd.debian.binary-package",
	".udeb": "application/vnd.debian.binary-package",
	".db": "application/vnd.sqlite3",
	".sqlite": "application/vnd.sqlite3",
	".sqlite3": "application/vnd.sqlite3",
	".db-wal": "application/vnd.sqlite3",
	".sqlite-wal": "application/vnd.sqlite3",
	".db-shm": "application/vnd.sqlite3",
	".sqlite-shm": "application/vnd.sqlite3",
	".boz": "application/x-bzip2",
	".kra": "application/x-krita",
	".krz": "application/x-krita",
	".tex": "application/x-tex",
	".latex": "application/x-latex",
	".bat": "application/x-msdownload",
	".exe": "application/x-msdownload",
	".dll": "application/x-msdownload",
	".com": "application/x-msdownload",
	".msi": "application/x-msdownload",
	".pl": "application/x-perl",
	".pn": "application/x-perl",
	".pyc": "application/x-python-code",
	".pyo": "application/x-python-code",
	".rpa": "application/x-redhat-package-manager",
	".rpm": "application/x-rpm",
	".crt": "application/x-x509-ca-cert", // Mine is .pem lol
	".der": "application/x-x509-ca-cert",
	".xpdl": "application/xml",
	".xsl": "application/xml",
	".3gp": "audio/3gpp",
	".3g2": "video/3gpp2", // Fuck it am going with video
	".aiff": "audio/aiff", // still wondering why do we have x-Type
	".flac": "audio/flac",
	".midi": "audio/midi",
	".mid": "audio/midi",
	".kar": "audio/midi",
	".rmi": "audio/midi",
	".opus": "audio/opus",
	// No chemical type here wtf is that
	".woff": "font/woff",
	".woff2": "font/woff2",
	".avif": "image/avif",
	".jpe": "image/jpeg",
	// Adding the long dead kodak mimes might me interesting but nah
	".rgb": "image/x-rgb",
	".pjpg": "image/jpeg",
	".jfi": "image/jpeg",
	".jfif-tbnl": "image/jpeg",
	".jpeg": "image/jpeg",
	".jpg": "image/jpeg",
	".jif": "image/jpeg",
	".ics": "text/calendar",
	".ifb": "text/calendar",
	".md": "text/markdown",
	".markdown": "text/markdown",
	".mdown": "text/markdown",
	".markdn": "text/markdown",
	".mml": "text/mathml",
	".mathml": "text/mathml",
	// People who uses any file extension that isnt .txt for text files are psychopaths
	".def": "text/plain", 
	".conf": "text/plain", 
	".diff": "text/plain", 
	".in": "text/plain", 
	".ksh": "text/plain", 
	".log": "text/plain", // This one is acceptable
	".list": "text/plain",
	".text": "text/plain",
	".rtx": "text/richtext",
	".uri": "text/uri-list",
	".urls": "text/uri-list",
	".uris": "text/uri-list",
	".p": "text/x-pascal", // Hi grandpas
	".pp": "text/x-pascal",
	".pas": "text/x-pascal",
	".inc": "text/x-pascal",
	".py": "text/x-python",
	".ext": "text/x-setext",
	".h261": "video/h261",
	".h263": "video/h263",
	".h264": "video/h264",
	".jpgv": "video/jpeg", // didnt knew they had videos
	".jpgm": "video/jpm",
	".jpm": "video/jpm",
	".mp4v": "video/mp4",
	".mpg4": "video/mp4",
	".m1v": "video/mpeg",
	".m2v": "video/mpeg",
	".mpa": "video/mpeg",
	".mpe": "video/mpeg",
	"mpg": "video/mpeg",
	".m4v": "video/x-m4v",
	".mkv": "video/x-matroska",
}

func GetMimeByExt(p string) string {
	if mime, ok := mimeTypes[filepath.Ext(p)]; ok {
		return mime
	} else {
		return "application/octet-stream"
	}
}
